# for date normalisation

dict_month_name_to_nb = {
    "janvier": "01",
    "janv": "01",
    "jan": "01",
    "février": "02",
    "fév": "02",
    "mars": "03",
    "avril": "04",
    "avr": "04",
    "mai": "05",
    "juin": "06",
    "juillet": "07",
    "juil": "07",
    "août": "08",
    "septembre": "09",
    "sept": "09",
    "octobre": "10",
    "oct": "10",
    "novembre": "11",
    "nov": "11",
    "décembre": "12",
    "déc": "12",
}
date_format = [
    "%d/%m/%Y",
    "%d-%m-%Y",
    "%d.%m.%Y",
    "%d:%m:%Y",
    "%d/%m/%y",
    "%d-%m-%y",
    "%d.%m.%y",
    "%d:%m:%y",
]
