name: Documentation

on:
  push:
    branches: [main]

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Set PY variable
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -e '.[docs]'

      - name: Set up Git
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
      - name: Build documentation
        run: |
          git fetch origin gh-pages
          mike delete main
          mike deploy --push main
